name: CICD

on:
  push:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t nandkumarmohite/my-first-docker-repository

      - name: Publish image to docker hub
        run: docker push nandkumarmohite/my-first-docker-repository:latest

  deploy:
    needs: build
    runs-on: aws-ec2

    steps:
      - name: Pull Image from docker hub
        run: docker pull nandkumarmohite/my-first-docker-repository:latest

      - name: Delete old container
        run: docker rm -f springboot-example-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-example-container nandkumarmohite/my-first-docker-repository